
service: react-todo-app-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1


functions:
  products:
    handler: handler.products
    environment:
      DB_HOST: ${opt:DB_HOST}
      DB_USER: ${opt:DB_USER}
      DB_PASSWORD: ${opt:DB_PASSWORD}
    events:
      - http:
          path: products
          method: get
          cors: true
      - http:
          path: products
          method: post
          cors: true
      - http:
          path: products/{item_id}
          method: put
          cors: true
      - http:
          path: products/{item_id}
          method: delete
          cors: true
      
